site_name: Markdown_作品集

nav:
  - 介绍: index.md
  - 作品集: 
    - 作品集概览: portfolio/index.md
    - API文档: portfolio/API-documentation.md
    - 用户手册: portfolio/how-to-guide.md
    - 版本指南: portfolio/release-notes.md
    - 用户教程: portfolio/tutorial.md
    - 工具文档: portfolio/madcap-flare-operation-guide.md
  - 简历:
    - 中文简历: resume.md
    - English: resume-en.md
  - 学习笔记:
    - Markdown 基础语法: notes/markdown-syntax-basic.md
    - Markdown 扩展语法: notes/markdown-syntax-extended.md
    - MkDocs FAQ: notes/mkdocs-faq.md


theme: mkdocs


extra_css:
  - styles/custom.css

markdown_extensions:
  - admonition
  # 删除线和下标
  - pymdownx.tilde
  # 上标
  - pymdownx.caret
  # 高亮
  - pymdownx.mark
  # 任务列表
  - pymdownx.tasklist:
      custom_checkbox: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list  

Extra:
  analytics:
    provider: google
    property: G-4TV7P06J8L